# Generated by Django 5.1 on 2024-10-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfi', '0002_transactiontype_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactiontype',
            old_name='default',
            new_name='is_default',
        ),
        migrations.AddField(
            model_name='category',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
